export interface BrowserExtension {
  name: string
  description: string
  why: string
  url: string
  icon: string
}

export const browserExtensions: BrowserExtension[] = [
  {
    name: "TruffleHog",
    description: "Find hidden API keys and secrets on web pages automatically",
    why: "Scans pages for exposed credentials — essential for ethical hackers",
    url: "https://chromewebstore.google.com/detail/trufflehog/bafhdnhjnlcdbjcdcnafhdcphhnfnhjc",
    icon: "search",
  },
  {
    name: "FoxyProxy",
    description: "Proxy management for Burp Suite, OWASP ZAP and MITM tools",
    why: "Easily switch between proxy configurations for intercepting traffic",
    url: "https://chromewebstore.google.com/detail/foxyproxy/gcknhkkoolaabfmlnjonogaaifnjlfnp",
    icon: "globe",
  },
  {
    name: "Wappalyzer",
    description: "Identify technology stack — frameworks, CMS, server details",
    why: "Quickly analyze a site's backend for recon and vulnerability mapping",
    url: "https://chromewebstore.google.com/detail/wappalyzer-technology-pro/gppongmhjkpfnbhagpmjfkannfbllamg",
    icon: "zap",
  },
  {
    name: "Temp-Mail",
    description: "Disposable temporary email addresses for testing",
    why: "Avoid spam and register on sites without using personal email",
    url: "https://chromewebstore.google.com/detail/temp-mail-disposable-temp/inojafojbhdpnehkhhfjalgjjobnhomj",
    icon: "mail",
  },
  {
    name: "Hunter.io",
    description: "Extract publicly available emails from websites",
    why: "Gather contact info for responsible disclosure and OSINT",
    url: "https://chromewebstore.google.com/detail/hunter-email-finder-exten/hgmhmanijnjhaffoampdlllchpolkdnj",
    icon: "search",
  },
  {
    name: "HackTools",
    description: "Payload generator with pre-built SQLi, XSS and more",
    why: "Pre-built payloads save time during manual testing",
    url: "https://chromewebstore.google.com/detail/hack-tools/cmbndhnoonmghfofefkcccljbkdpamhi",
    icon: "zap",
  },
  {
    name: "EditThisCookie",
    description: "Advanced cookie editor — modify, delete, manage cookies",
    why: "Analyze session tokens, check HTTPOnly and Secure flags",
    url: "https://chromewebstore.google.com/detail/editthiscookie-v3/ojfebgpkimhlhcblbalbfjblapadhbol",
    icon: "shield",
  },
  {
    name: "WebRTC Protect",
    description: "Prevent IP address leakage via WebRTC",
    why: "Essential for anonymous browsing and VPN users",
    url: "https://chromewebstore.google.com/detail/webrtc-protect-protect-ip/bkmmlbllpjdpgcgdohbaghfaecnddhni",
    icon: "shield",
  },
  {
    name: "Link Gopher",
    description: "Extract all links from a webpage in bulk",
    why: "URL extraction for reconnaissance and application mapping",
    url: "https://chromewebstore.google.com/detail/link-gopher/bpjdkodgnbfalgghnbeggfbfjpcfamkf",
    icon: "link",
  },
  {
    name: "FindSomething",
    description: "Scan source code and JS files for hidden data and API keys",
    why: "Identifies sensitive info like credentials in JavaScript",
    url: "https://chromewebstore.google.com/detail/findsomething/kfhniponecokdefffkpagipffdefeldb",
    icon: "search",
  },
  {
    name: ".git Finder",
    description: "Detect exposed .git directories leading to source code leaks",
    why: "Easy way to find information disclosure vulnerabilities",
    url: "https://chromewebstore.google.com/detail/dotgit/pampamgoihgcedonnphgehgondkhikel",
    icon: "folder-search",
  },
  {
    name: "Open Multiple URLs",
    description: "Open multiple links simultaneously to save time",
    why: "Automates mass link opening for bug hunting tasks",
    url: "https://chromewebstore.google.com/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh",
    icon: "link",
  },
  {
    name: "uBlock Origin",
    description: "Block ads, trackers and malicious scripts",
    why: "Improves privacy and blocks potentially malicious content",
    url: "https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm",
    icon: "shield",
  },
  {
    name: "Dark Reader",
    description: "Dark mode for all websites — reduces eye strain",
    why: "Helpful for night-time bug hunting with customizable settings",
    url: "https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh",
    icon: "moon",
  },
  {
    name: "UA Switcher",
    description: "Spoof user-agents to test websites on different platforms",
    why: "Bypass bot detection and test behavior across platforms",
    url: "https://chromewebstore.google.com/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg",
    icon: "globe",
  },
  {
    name: "EXIF Viewer Pro",
    description: "Extract image metadata without downloading",
    why: "Retrieve camera, location, timestamps — useful for OSINT",
    url: "https://chromewebstore.google.com/detail/exif-viewer-pro/mmbhfeiddhndihdjeganjggkmjapkffm",
    icon: "image",
  },
  {
    name: "Traduzir Paginas Web",
    description: "Translate entire web pages into different languages",
    why: "Analyze foreign websites for vulnerabilities across languages",
    url: "https://chromewebstore.google.com/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb",
    icon: "globe",
  },
  {
    name: "Wayback Machine",
    description: "Fetch archived URLs from Wayback Machine",
    why: "Identify past versions and previously exposed vulnerabilities",
    url: "https://chromewebstore.google.com/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak",
    icon: "clock",
  },
  {
    name: "SponsorBlock",
    description: "Skip YouTube sponsors, intros and outros automatically",
    why: "Saves time while learning from cybersecurity content",
    url: "https://chromewebstore.google.com/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone",
    icon: "zap",
  },
  {
    name: "Shodan",
    description: "Website intelligence — hosting, server locations, open ports",
    why: "Identify exposed services and security misconfigurations",
    url: "https://chromewebstore.google.com/detail/shodan/jjalcfnidlmpjhdfepjhjbhnhkbgleap",
    icon: "search",
  },
  {
    name: "EndPointer",
    description: "Extract and analyze URLs for sensitive endpoints",
    why: "Locate sensitive web app endpoints for fuzzing and testing",
    url: "https://chromewebstore.google.com/detail/endpointer/ppliilneafplhagjhhphcjmjdmbjagcp",
    icon: "target",
  },
  {
    name: "YesWeHack VDP Finder",
    description: "Detect vulnerability disclosure programs of visited sites",
    why: "Find public bug bounty programs and report responsibly",
    url: "https://chromewebstore.google.com/detail/yeswehack-vdp-finder/jnknjejacdkpnaacfgolbmdohkhpphjb",
    icon: "shield",
  },
  {
    name: "S3BucketList",
    description: "Search and list AWS S3 buckets from network requests",
    why: "Identify publicly accessible and misconfigured S3 buckets",
    url: "https://chromewebstore.google.com/detail/s3bucketlist/anngjobjhcbancaaogmlcffohpmcniki",
    icon: "cloud",
  },
  {
    name: "D3coder",
    description: "Encode/decode tool for Base64, URL encoding and more",
    why: "Quickly convert encoded payloads during testing",
    url: "https://chromewebstore.google.com/detail/d3coder/gncnbkghencmkfgeepfaonmegemakcol",
    icon: "code",
  },
  {
    name: "Mitaka",
    description: "OSINT search — IPs, domains, URLs, hashes across platforms",
    why: "Speed up investigations with multi-platform threat intel",
    url: "https://chromewebstore.google.com/detail/mitaka/bfjbejmeoibbdpfdbmbacmefcbannnbg",
    icon: "search",
  },
  {
    name: "Vortimo",
    description: "OSINT swiss-army knife — bookmark, scrape, analyze pages",
    why: "Store findings, highlight text, correlate across pages",
    url: "https://chromewebstore.google.com/detail/vortimo-osint-tool/mnakbpdnkedaegeiaoakkjafhoidklnf",
    icon: "brain",
  },
  {
    name: "Toggle JavaScript",
    description: "Enable/disable JavaScript for testing client-side vs server-side",
    why: "Test JS-dependent flaws like XSS and bypass client validations",
    url: "https://chromewebstore.google.com/detail/toggle-javascript/cidlcjdalomndpeagkjpnefhljffbnlo",
    icon: "code",
  },
  {
    name: "IP Address and Domain Info",
    description: "Quick lookup — IP, hosting provider, geolocation, WHOIS",
    why: "Instant recon with ASN, IP geolocation and WHOIS data",
    url: "https://chromewebstore.google.com/detail/ip-address-and-domain-inf/lhgkegeccnckoiliokondpaaalbhafoa",
    icon: "globe",
  },
  {
    name: "JSON Formatter",
    description: "Format and highlight raw JSON data in the browser",
    why: "Read API responses clearly during recon and debugging",
    url: "https://chromewebstore.google.com/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa",
    icon: "code",
  },
  {
    name: "HackBar",
    description: "Manual testing — encode/decode URLs, inject payloads",
    why: "Quickly test XSS, SQLi and other injections in the browser",
    url: "https://chromewebstore.google.com/detail/hackbar/ginpbkfigcoaokgflihfhhmglmbchinc",
    icon: "zap",
  },
  {
    name: "Fake Filler",
    description: "Auto-fill forms with realistic dummy data",
    why: "Speed up form exploration during recon and bug reproduction",
    url: "https://chromewebstore.google.com/detail/fake-filler/bnjjngeaknajbdcgpfkgnonkmififhfo",
    icon: "edit",
  },
  {
    name: "Code Formatter",
    description: "Pretty-print JSON, CSS and JS in the browser",
    why: "Spot config values, keys or suspicious strings faster",
    url: "https://chromewebstore.google.com/detail/code-formatter-json-css-j/bhimnoepicmcjfkbmhckamllnibadfal",
    icon: "code",
  },
  {
    name: "rep+",
    description: "Capture, modify, and replay HTTP requests in Chrome DevTools with AI-powered security analysis",
    why: "Burp Suite Repeater functionality directly in browser — no proxy setup, with AI analysis",
    url: "https://chromewebstore.google.com/detail/rep+/dhildnnjbegaggknfkagdpnballiepfm",
    icon: "edit",
  },
]
