export interface EncodingFormat {
  slug: string
  name: string
  description: string
  category: string
  howItWorks: string
  algorithm: string
  examples: { input: string; output: string }[]
  securityUseCases: string[]
  relatedSlugs: string[]
  notes: string
}

export const encodingFormats: EncodingFormat[] = [
  {
    slug: "base64",
    name: "Base64",
    description: "Standard Base64 encoding as defined in RFC 4648",
    category: "Binary-to-Text",
    howItWorks: "Base64 converts binary data into an ASCII string by grouping 6 bits at a time and mapping each 6-bit value to a character in the A-Z, a-z, 0-9, +, / alphabet. Padding with = is added to make the output length a multiple of 4.",
    algorithm: "Each 3 bytes (24 bits) of input are split into four 6-bit groups, each mapped to a Base64 character. If fewer than 3 bytes remain, the output is padded with = characters.",
    examples: [
      { input: "hello", output: "aGVsbG8=" },
      { input: "test123", output: "dGVzdDEyMw==" },
      { input: "Hello World", output: "SGVsbG8gV29ybGQ=" },
    ],
    securityUseCases: [
      "JWT tokens use Base64URL (a variant) for header and payload encoding",
      "Basic Auth credentials are Base64-encoded (username:password)",
      "Common in API payloads, cookies, and hidden form fields",
      "Used to exfiltrate data in XSS payloads when special chars are blocked",
      "Often found in web application tokens and session identifiers",
    ],
    relatedSlugs: ["base64url", "base32", "base58", "base85"],
    notes: "Standard Base64 uses + and / which can cause issues in URLs. The = padding can be a signature for detection. Always check for Base64-encoded strings during reconnaissance.",
  },
  {
    slug: "base64url",
    name: "Base64URL",
    description: "URL-safe Base64 encoding without padding",
    category: "Binary-to-Text",
    howItWorks: "Same as Base64 but replaces + with - and / with _, and omits = padding characters to make the output safe for use in URLs and filenames without escaping.",
    algorithm: "Same grouping as Base64 (3 bytes → 4 chars), but uses a different last two characters: - replaces +, _ replaces /. Padding = is stripped entirely.",
    examples: [
      { input: "hello", output: "aGVsbG8" },
      { input: "test123", output: "dGVzdDEyMw" },
      { input: "Hello World", output: "SGVsbG8gV29ybGQ" },
    ],
    securityUseCases: [
      "JWT (JSON Web Tokens) exclusively use Base64URL for all three segments",
      "Used in OAuth 2.0 and OpenID Connect tokens",
      "Common in API parameters where standard Base64 would break URLs",
      "Found in password reset tokens and email verification links",
      "Used by some malware C2 channels to encode exfiltrated data",
    ],
    relatedSlugs: ["base64", "base32", "base58", "base85"],
    notes: "JWT segments are always Base64URL without padding. Decoding a JWT without a library can be done by splitting on dots, adding padding back, and decoding each Base64URL segment.",
  },
  {
    slug: "base32",
    name: "Base32",
    description: "RFC 4648 Base32 encoding",
    category: "Binary-to-Text",
    howItWorks: "Base32 converts binary data into an ASCII string using an alphabet of A-Z and 2-7 (32 characters). Each 5 bits map to one character, making it more human-readable than Base64 but less space-efficient (overhead ~40%).",
    algorithm: "Input bytes are processed in 5-byte (40-bit) groups, split into eight 5-bit values, each mapped to a character from A-Z (0-25) and 2-7 (26-31). Padding with = makes output length a multiple of 8.",
    examples: [
      { input: "hello", output: "NBSWY3DP" },
      { input: "test", output: "ORSXG5A=" },
      { input: "f", output: "MY======" },
    ],
    securityUseCases: [
      "Used in TOTP (Time-based One-Time Password) secrets — Google Authenticator",
      "Found in some VPN configuration files and license keys",
      "Used by malware for data exfiltration when Base64 is blocked",
      "Common in 2FA recovery codes and backup tokens",
      "Occasionally used to obfuscate strings in web applications",
    ],
    relatedSlugs: ["base64", "base64url", "base58", "base85"],
    notes: "Base32 is case-insensitive (only uppercase) and uses A-Z,2-7. It's recognizable by its uppercase letters and digits only (no lowercase, no + or /). Can be identified by the = padding pattern (multiples of 8).",
  },
  {
    slug: "base58",
    name: "Base58",
    description: "Bitcoin-style Base58 encoding",
    category: "Binary-to-Text",
    howItWorks: "Base58 removes visually similar characters (0, O, I, l) from Base64 to avoid ambiguity. Used primarily in cryptocurrency addresses. The alphabet is 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz.",
    algorithm: "The input is treated as a big-endian number and converted to base-58 using the Bitcoin alphabet. Leading zero bytes are represented as a '1' character each.",
    examples: [
      { input: "hello", output: "AxQmu7hB" },
      { input: "test", output: "3yZe7d" },
      { input: "abc", output: "ZiCa" },
    ],
    securityUseCases: [
      "Bitcoin addresses and wallet import formats use Base58Check (Base58 + checksum)",
      "Found in blockchain explorers and cryptocurrency-related apps",
      "Some CTF challenges use Base58 to encode flags or secrets",
      "Used in Ripple and other cryptocurrency address formats",
      "Occasionally found in web apps dealing with crypto payments",
    ],
    relatedSlugs: ["base64", "base64url", "base32", "base85"],
    notes: "Base58 is not as universally supported in standard libraries. You'll need custom decoding. The 'Base58Check' variant adds a 4-byte checksum (double SHA-256 prefix) for error detection — used in Bitcoin addresses.",
  },
  {
    slug: "base85",
    name: "Base85 / Ascii85",
    description: "Adobe Ascii85 encoding",
    category: "Binary-to-Text",
    howItWorks: "Base85 encodes binary data using 85 printable ASCII characters, achieving ~25% overhead (better than Base64's ~33%). The Adobe version uses characters from ! to u and wraps output in <~ and ~> delimiters.",
    algorithm: "4 bytes (32 bits) of input are converted to a 5-digit base-85 number. Each digit maps to a character from ! (33) to u (117). Zero bytes are compressed to 'z' for efficiency. Output is enclosed in <~ ~>.",
    examples: [
      { input: "hello", output: "<~BOu!rDZ~>" },
      { input: "test", output: "<~F%3Mk~>" },
      { input: "abc", output: "<~@:E4~>" },
    ],
    securityUseCases: [
      "Used in PDF files for encoding binary streams and images",
      "Found in PostScript files and some document formats",
      "Occasionally used in CTF challenges to hide data",
      "Can appear in embedded resources in legacy file formats",
      "Used by some malware to encode payloads in documents",
    ],
    relatedSlugs: ["base64", "base64url", "base58", "base32"],
    notes: "Adobe Ascii85 uses <~ and ~> as delimiters. The 'z' character represents 4 zero bytes (compression). Not all Base85 implementations are compatible — there are several variants (Adobe, Z85, RFC 1924, etc.).",
  },
  {
    slug: "url",
    name: "URL Encoding",
    description: "Percent-encoding for URLs as defined in RFC 3986",
    category: "Web",
    howItWorks: "URL encoding converts characters that are not allowed in URLs to a % followed by two hexadecimal digits representing the character's byte value. Reserved characters (:, /, ?, #, etc.) and non-ASCII bytes are percent-encoded.",
    algorithm: "Each byte of a character (in UTF-8) that is not unreserved (A-Z, a-z, 0-9, -, _, ., ~) is replaced with %XX where XX is the hex value of that byte. Spaces are commonly encoded as %20 or + (in application/x-www-form-urlencoded).",
    examples: [
      { input: "hello world", output: "hello%20world" },
      { input: "a&b=c", output: "a%26b%3Dc" },
      { input: "test/1", output: "test%2F1" },
    ],
    securityUseCases: [
      "All web requests use URL encoding for query parameters and form data",
      "Double URL encoding can bypass WAF filters (e.g., %253e instead of %3e for >)",
      "Used in SSRF attacks to encode internal hostnames or schemes",
      "SQL injection payloads are often URL-encoded to evade detection",
      "XSS filter bypasses frequently use nested URL encoding",
    ],
    relatedSlugs: ["url-double", "html-hex", "unicode-escape"],
    notes: "Always check for decoded and encoded versions during testing. Server-side decoding order matters — some apps decode multiple times. The + character is treated as a space in query strings but not in URL paths.",
  },
  {
    slug: "url-double",
    name: "Double URL Encoding",
    description: "Double percent-encoding for WAF bypass",
    category: "Web",
    howItWorks: "Double URL encoding applies percent-encoding twice to the same character. For example, < becomes %3C, then %3C becomes %253C (the % itself is encoded to %25). This can bypass single-decoding WAF filters.",
    algorithm: "Take the URL-encoded form of a character, then URL-encode the % character itself. % → %25, so %3C (for <) becomes %253C when double-encoded.",
    examples: [
      { input: "<script>", output: "%253Cscript%253E" },
      { input: "' OR '1'='1", output: "%2527%2520OR%2520%25271%2527%253D%25271" },
      { input: "../etc", output: "..%252Fetc" },
    ],
    securityUseCases: [
      "WAF bypass — many WAFs decode once, if the server decodes twice the payload bypasses",
      "LFI/RFI attacks — double-encode ../ to ..%252f to bypass path traversal filters",
      "SQL injection — double-encode quotes and operators to evade detection",
      "SSRF bypass — double-encode localhost or internal IP patterns",
      "XSS filter evasion — double-encode angle brackets and event handlers",
    ],
    relatedSlugs: ["url", "html-hex", "unicode-escape"],
    notes: "Works only when the server performs double decoding (e.g., through URL rewrite modules or multiple layers). Test both single and double encoded versions. Apache mod_rewrite and IIS URL Rewrite modules are common double-decoders.",
  },
  {
    slug: "html",
    name: "HTML Entity Encoding",
    description: "HTML entity encoding for safe rendering",
    category: "Web",
    howItWorks: "HTML entities replace special characters with named or numeric references that browsers render as the original character. < becomes &lt; and > becomes &gt;. Also, any character can be encoded as &#DDD; (decimal) or &#xHH; (hex).",
    algorithm: "Special HTML characters (<, >, &, \", ') are replaced with their named entities (&lt;, &gt;, &amp;, &quot;, &#39;). All other characters can be encoded as &#DECIMAL; or &#xHEX; using their Unicode code point.",
    examples: [
      { input: "<script>", output: "&lt;script&gt;" },
      { input: "a & b", output: "a &amp; b" },
      { input: "hello", output: "&#104;&#101;&#108;&#108;&#111;" },
    ],
    securityUseCases: [
      "HTML encoding is the primary defense against XSS — encode untrusted data",
      "Some XSS contexts require bypassing HTML entity encoding (e.g., in tag attributes)",
      "WAFs may block <script> but not &lt;script&gt; — useful for detection probes",
      "HTML entities can encode entire payloads to evade string-matching filters",
      "Decode HTML entities when analyzing reflected input in parameter values",
    ],
    relatedSlugs: ["html-hex", "html-dec", "unicode-escape"],
    notes: "HTML entity encoding is context-sensitive. What works in HTML body context does NOT work in script, attribute, or URL contexts. Always check the rendering context when testing XSS.",
  },
  {
    slug: "html-hex",
    name: "HTML Hex Entity",
    description: "HTML hex entity encoding (&#xHH;)",
    category: "Web",
    howItWorks: "Each character is encoded as &#xHH; where HH is the Unicode code point in hexadecimal. Unlike named entities, hex entities can represent any Unicode character and are more compact than decimal entities.",
    algorithm: "For each character, get its Unicode code point as a hexadecimal number, then format as &#xHH;. For example, A (U+0041) becomes &#x41;. The hex digits are case-insensitive but commonly uppercase.",
    examples: [
      { input: "hello", output: "&#x68;&#x65;&#x6C;&#x6C;&#x6F;" },
      { input: "XSS", output: "&#x58;&#x53;&#x53;" },
      { input: "<>", output: "&#x3C;&#x3E;" },
    ],
    securityUseCases: [
      "XSS bypass — hex entities are decoded in HTML context but not in all contexts",
      "Can bypass WAF rules that look for specific keywords (&#x53;cript for Script)",
      "Useful for obfuscating payloads in HTML injection scenarios",
      "Common in DOM-based XSS where innerHTML is used",
      "Some filters block decimal entities but forget hex variants",
    ],
    relatedSlugs: ["html", "html-dec", "unicode-escape"],
    notes: "Hex entities are decoded by the HTML parser before JavaScript execution. They work in HTML body and attribute contexts but NOT inside <script> tags. Always test both hex and decimal variants for filter bypass.",
  },
  {
    slug: "html-dec",
    name: "HTML Decimal Entity",
    description: "HTML decimal entity encoding (&#DDD;)",
    category: "Web",
    howItWorks: "Same concept as hex entities but uses decimal numbers: &#DDD;. Each character's Unicode code point is expressed in decimal rather than hexadecimal. Can represent all Unicode characters.",
    algorithm: "For each character, get its Unicode code point as a decimal number, then format as &#DDD;. For example, A (U+0041 = 65) becomes &#65;. Number values can range from 0 to 1,114,111.",
    examples: [
      { input: "hello", output: "&#104;&#101;&#108;&#108;&#111;" },
      { input: "XSS", output: "&#88;&#83;&#83;" },
      { input: "<>", output: "&#60;&#62;" },
    ],
    securityUseCases: [
      "Classic XSS filter bypass — many filters only check for < and >, not &#60; and &#62;",
      "Can encode entire payloads to evade content inspection filters",
      "Useful in HTML injection where the app blocks 'bad' characters",
      "Some WAFs have different rules for decimal vs hex entities",
      "Common in email XSS and rich text injection vectors",
    ],
    relatedSlugs: ["html", "html-hex", "unicode-escape"],
    notes: "Decimals without leading zeros (&#65; not &#0065;). Some parsers accept missing semicolons in certain contexts (e.g., &#65 for A). HTML entities without semicolons can still be parsed in some browsers.",
  },
  {
    slug: "hex",
    name: "Hex (no spaces)",
    description: "Hexadecimal encoding without spaces",
    category: "Binary-to-Text",
    howItWorks: "Each byte of the input is converted to a two-digit hexadecimal number and concatenated without any separator. Commonly used to represent binary data in a human-readable hex format.",
    algorithm: "For each character, get its byte value (character code for ASCII, or UTF-8 bytes for non-ASCII) and format as two hex digits: 0-9, A-F. No spaces or delimiters between bytes.",
    examples: [
      { input: "hello", output: "68656C6C6F" },
      { input: "test", output: "74657374" },
      { input: "ABC", output: "414243" },
    ],
    securityUseCases: [
      "Often used in URL parameters, cookies, and hidden form fields",
      "Common encoding for binary data in web applications",
      "Used in some authentication tokens and session identifiers",
      "Can hide plaintext strings from casual inspection",
      "Frequently used in CTF challenges and malware configuration data",
    ],
    relatedSlugs: ["hex-spaces", "binary", "base64"],
    notes: "Easily recognizable: even length, 0-9 A-F only. Each byte produces 2 hex chars. Case-insensitive. The most common hex encoding format in web applications.",
  },
  {
    slug: "hex-spaces",
    name: "Hex (with spaces)",
    description: "Hexadecimal encoding with space separators",
    category: "Binary-to-Text",
    howItWorks: "Same hex conversion as plain hex, but each byte pair is separated by a space for readability. Commonly seen in hex dumps, network packet captures, and binary analysis.",
    algorithm: "Same as plain hex but insert a space between each two-byte group. For example, 68656C6C6F becomes 68 65 6C 6C 6F. Some formats also prepend 0x per byte or use other delimiters.",
    examples: [
      { input: "hello", output: "68 65 6C 6C 6F" },
      { input: "test", output: "74 65 73 74" },
      { input: "ABC", output: "41 42 43" },
    ],
    securityUseCases: [
      "Found in intercepted traffic and debug output",
      "Wireshark and tcpdump output use space-separated hex",
      "Memory dumps and stack traces use this format",
      "Some web apps format hex this way for log display",
      "Used in network protocol analyzers and security tools",
    ],
    relatedSlugs: ["hex", "binary", "base64"],
    notes: "Always normalize hex by removing spaces before comparison. Also look for formats like 0x68 0x65 0x6C or \\x68\\x65\\x6C — these are variants with different delimiters.",
  },
  {
    slug: "unicode-escape",
    name: "Unicode \\u Escapes",
    description: "Unicode escape sequences (\\uXXXX)",
    category: "Text",
    howItWorks: "JavaScript-style Unicode escape sequences represent each character as \\u followed by 4 hexadecimal digits of its Unicode code point. Used in JavaScript strings and JSON data.",
    algorithm: "For each character, get its Unicode code point (U+HHHH) and format as \\uHHHH. Characters outside the Basic Multilingual Plane (BMP) are encoded as surrogate pairs (\\\\uD800-\\\\uDFFF).",
    examples: [
      { input: "hello", output: "\\u0068\\u0065\\u006C\\u006C\\u006F" },
      { input: "XSS", output: "\\u0058\\u0053\\u0053" },
      { input: "<>", output: "\\u003C\\u003E" },
    ],
    securityUseCases: [
      "XSS filter bypass — \\u003C is decoded by JavaScript parsers before code executes",
      "JSON data commonly uses \\u escapes for special characters",
      "Can bypass WAF rules that don't normalize Unicode escapes before pattern matching",
      "JavaScript Unicode escapes work in string literals and identifier names",
      "Some code review tools miss \\u-encoded malicious code",
    ],
    relatedSlugs: ["html-hex", "unicode-codepoint", "js-hex"],
    notes: "JavaScript processes \\u escapes in string literals. \\u003C is the same as <. Also see \\x escapes (2 hex digits for bytes) and \\u{HEX} in modern JS (ES6+) for code points beyond U+FFFF.",
  },
  {
    slug: "unicode-codepoint",
    name: "Unicode Code Point (U+HHHH)",
    description: "Unicode code point notation (U+HHHH)",
    category: "Text",
    howItWorks: "The formal Unicode notation lists each character as U+ followed by its hexadecimal code point. Used in Unicode standards documentation, character tables, and internationalization contexts.",
    algorithm: "Each character is represented as U+XXXXXX where the hex digits represent its Unicode code point (1-6 hex digits). For example, the letter A is U+0041, and the emoji 😀 is U+1F600.",
    examples: [
      { input: "A", output: "U+0041" },
      { input: "hello", output: "U+0068 U+0065 U+006C U+006C U+006F" },
      { input: "😀", output: "U+1F600" },
    ],
    securityUseCases: [
      "Understanding Unicode normalization attacks (NFD vs NFC)",
      "Homoglyph attacks use visually similar Unicode characters to trick users",
      "IDN homograph attacks register domains with lookalike Unicode chars",
      "Character encoding confusion can bypass input validation filters",
      "Used in analyzing Unicode normalization vulnerabilities in parsers",
    ],
    relatedSlugs: ["unicode-escape", "utf8-bytes", "html-hex"],
    notes: "U+0041 and U+0061 are different (uppercase vs lowercase A). Unicode normalization (NFC, NFD, NFKC, NFKD) can transform characters — a security issue when validation and display use different normalizations.",
  },
  {
    slug: "utf8-bytes",
    name: "UTF-8 Bytes",
    description: "UTF-8 byte sequence representation",
    category: "Binary-to-Text",
    howItWorks: "Shows the raw UTF-8 byte sequence of a string as hex bytes. UTF-8 encodes Unicode characters as 1-4 bytes. ASCII characters (U+0000-U+007F) use 1 byte, while higher code points use 2-4 bytes.",
    algorithm: "Each character is encoded to its UTF-8 byte sequence using TextEncoder. Each byte is shown as a two-digit hex value. Multi-byte sequences follow the UTF-8 encoding rules (0xxxxxxx, 110xxxxx 10xxxxxx, etc.).",
    examples: [
      { input: "hello", output: "68 65 6C 6C 6F" },
      { input: "héllo", output: "68 C3 A9 6C 6C 6F" },
      { input: "😀", output: "F0 9F 98 80" },
    ],
    securityUseCases: [
      "Understanding how UTF-8 encoding affects input validation and filter length limits",
      "UTF-8 overlong sequences can bypass security checks (e.g., '/cgi-bin/' encoded as overlong UTF-8)",
      "Identify encoding issues in web applications that mix character sets",
      "Analyze how different browsers interpret malformed UTF-8 sequences",
      "Useful for WAF bypass when the WAF and app disagree on UTF-8 decoding",
    ],
    relatedSlugs: ["unicode-codepoint", "unicode-escape", "hex"],
    notes: "UTF-8 is the dominant encoding on the web. A single Unicode character can be anywhere from 1 to 4 bytes. Some security tools generate overlong UTF-8 sequences to test parser behavior.",
  },
  {
    slug: "js-hex",
    name: "JavaScript \\x Escapes",
    description: "JavaScript hex escape sequences (\\xHH)",
    category: "Text",
    howItWorks: "JavaScript \\x escapes allow encoding characters as \\x followed by 2 hex digits representing a byte value (0x00-0xFF). These escapes are interpreted by the JavaScript parser within string literals.",
    algorithm: "For each character with a code point below 256 (0x00-0xFF), format as \\xHH where HH is the two-digit hex value. Characters above U+00FF cannot be represented as \\x escapes.",
    examples: [
      { input: "hello", output: "\\x68\\x65\\x6C\\x6C\\x6F" },
      { input: "XSS", output: "\\x58\\x53\\x53" },
      { input: "<>", output: "\\x3C\\x3E" },
    ],
    securityUseCases: [
      "XSS filter bypass — \\x3Cscript\\x3E executes in eval or new Function contexts",
      "Used to obfuscate JavaScript payloads in web security testing",
      "Common in self-XSS and stored XSS where filters check literal angle brackets",
      "\\x escapes work in strings passed to setTimeout, setInterval, and eval",
      "Some CSP bypass techniques use \\x-encoded strings in inline scripts",
    ],
    relatedSlugs: ["unicode-escape", "hex", "binary"],
    notes: "\\x escapes only cover byte values 0x00-0xFF (one byte). For characters outside this range, use \\u escapes. \\x3C is equivalent to < in JavaScript string context.",
  },
  {
    slug: "morse",
    name: "Morse Code",
    description: "International Morse code encoding",
    category: "Text",
    howItWorks: "Morse code represents letters and numbers as sequences of dots (.) and dashes (-) separated by spaces. Letters within a word are separated by single spaces, words by forward slashes (/).",
    algorithm: "Each alphanumeric character is mapped to its Morse code pattern. Letters: A=.-, B=-..., C=-.-., etc. Numbers: 0=-----, 1=.----, etc. Words are separated by / and letters within words by single spaces.",
    examples: [
      { input: "SOS", output: "... --- ..." },
      { input: "hello", output: ".... . .-.. .-.. ---" },
      { input: "test 123", output: "- . ... - / .---- ..--- ...--" },
    ],
    securityUseCases: [
      "Used in CTF challenges to hide flags in audio, images, or text",
      "Some malware uses Morse-based C2 communication to evade detection",
      "Can appear in steganography challenges and puzzles",
      "Hidden in HTML comments, metadata, or image EXIF data",
      "Occasionally used in red team operations for covert signaling",
    ],
    relatedSlugs: ["binary", "base64"],
    notes: "Morse code is case-insensitive (uppercase only). International Morse excludes punctuation beyond basic . , ?. The timing-based version (audio) uses different lengths — text-based Morse uses spaces and slashes.",
  },
  {
    slug: "binary",
    name: "Binary (8-bit)",
    description: "8-bit binary representation",
    category: "Binary-to-Text",
    howItWorks: "Each character is represented as an 8-bit binary number (0s and 1s), showing the exact byte value in base-2. This is the lowest-level human-readable representation of data.",
    algorithm: "For each byte of input, convert the byte value (0-255) to an 8-digit binary number: 0b00000000 to 0b11111111. Most significant bit first (big-endian).",
    examples: [
      { input: "hello", output: "01101000 01100101 01101100 01101100 01101111" },
      { input: "A", output: "01000001" },
      { input: "test", output: "01110100 01100101 01110011 01110100" },
    ],
    securityUseCases: [
      "Understanding bit-level operations in cryptography and hash functions",
      "Analyzing network protocols at the binary level",
      "Reverse engineering and binary exploitation",
      "CTF challenges involving bit manipulation and binary analysis",
      "Low-level payload construction for buffer overflow exploits",
    ],
    relatedSlugs: ["hex", "octal", "base64"],
    notes: "Binary is the most verbose representation. 8 bits = 1 byte = 1 ASCII character. Non-ASCII characters take multiple bytes in UTF-8, so each byte is shown separately.",
  },
  {
    slug: "octal",
    name: "Octal Escapes",
    description: "Octal escape sequences (\\OOO)",
    category: "Text",
    howItWorks: "Octal representation encodes each byte as a 3-digit octal (base-8) number, often prefixed with a backslash in programming languages. PHP, Python, and Perl strings support octal escapes.",
    algorithm: "For each byte (0-255), convert to a 3-digit octal number (000-377). In PHP strings, format as \\OOO. Example: A (65 decimal) = 101 octal = \\101.",
    examples: [
      { input: "hello", output: "\\150\\145\\154\\154\\157" },
      { input: "A", output: "\\101" },
      { input: "<>", output: "\\074\\076" },
    ],
    securityUseCases: [
      "PHP string obfuscation — \\101\\155 equals 'Am' in PHP double-quoted strings",
      "Can bypass WAF rules that look for specific PHP function names",
      "Used in PHP code injection and webshell obfuscation",
      "Perl and Python also support octal escapes in strings",
      "Some older PHP payloads use octal to hide function calls",
    ],
    relatedSlugs: ["hex", "binary", "js-hex"],
    notes: "In PHP, octal escapes work in double-quoted strings only. \\101 is 'A'. Can be chained: \\150\\145\\154\\154\\157 = 'hello'. Python supports \\x00 and \\OOO escapes in strings.",
  },
  {
    slug: "rot13",
    name: "ROT13",
    description: "Caesar cipher with shift 13",
    category: "Cipher",
    howItWorks: "ROT13 rotates each letter by 13 positions in the alphabet. Since the alphabet has 26 letters, applying ROT13 twice returns the original text. It's self-inverse — the same function encodes and decodes.",
    algorithm: "A→N, B→O, ..., M→Z, N→A, O→B, ..., Z→M. Non-alphabetic characters are left unchanged. Case is preserved. ROT13 is equivalent to ROT13 (26-13) due to the 26-letter alphabet symmetry.",
    examples: [
      { input: "hello", output: "uryyb" },
      { input: "XSS", output: "KFF" },
      { input: "The quick brown fox", output: "Gur dhvpx oebja sbk" },
    ],
    securityUseCases: [
      "Commonly used in CTF challenges to hide clues and flags",
      "Used in some web applications for weak content obfuscation",
      "Found in forum posts and comments to hide spoilers or answers",
      "Caesar ciphers (including ROT13) are trivially breakable by frequency analysis",
      "Sometimes chained with Base64 or other encodings for multi-layer obfuscation",
    ],
    relatedSlugs: ["caesar", "base64", "reverse"],
    notes: "ROT13 is NOT encryption — it's a simple obfuscation. Always check for ROT13-encoded strings in CTFs and capture-the-flag challenges. It's self-inverse: applying ROT13 twice gives the original.",
  },
  {
    slug: "caesar",
    name: "Caesar Cipher",
    description: "Caesar cipher with selectable shift (ROT1-ROT25)",
    category: "Cipher",
    howItWorks: "The Caesar cipher shifts each letter by a fixed number of positions in the alphabet. ROT1 shifts A→B, ROT2 shifts A→C, etc. With 25 possible shifts (excluding ROT0), it's a simple substitution cipher.",
    algorithm: "Each letter is shifted by N positions (1-25). A shifted by 1 becomes B. Z shifted by 1 wraps around to A. Non-letters are preserved. Case is maintained. Decryption shifts by (26-N) in the opposite direction.",
    examples: [
      { input: "attack at dawn", output: "buubdl bu ebxo" },
      { input: "hello (ROT7)", output: "olssv" },
      { input: "XSS (ROT3)", output: "AVV" },
    ],
    securityUseCases: [
      "CTF challenges and puzzle solving",
      "Weak obfuscation in some legacy web applications",
      "Teaching tool for understanding substitution ciphers",
      "Sometimes used as one layer in multi-layer encoding chains",
      "Vulnerable to brute force (only 25 possible shifts) and frequency analysis",
    ],
    relatedSlugs: ["rot13", "reverse", "base64"],
    notes: "Brute-forcing all 25 shifts takes seconds manually and milliseconds with automation. Combine with frequency analysis (E, T, A are most common English letters). The shift wraps around the alphabet.",
  },
  {
    slug: "reverse",
    name: "Reverse String",
    description: "Character-level string reversal",
    category: "Text",
    howItWorks: "The entire string of characters is reversed end-to-end. This is a simple, non-destructive transformation. Combined with other encodings, it can be used for multi-layer obfuscation.",
    algorithm: "Take the input string and output the characters in reverse order. For example, 'hello' becomes 'olleh'. This works at the Unicode character level, not byte level, preserving multi-byte characters.",
    examples: [
      { input: "hello", output: "olleh" },
      { input: "XSS", output: "SSX" },
      { input: "12345", output: "54321" },
    ],
    securityUseCases: [
      "Often combined with Base64 for multi-layer encoding (e.g., reverse then Base64)",
      "Used in some malware strings to evade signature-based detection",
      "Obfuscation in web application parameters and tokens",
      "Reverse-then-Base64 is a common encoding pattern found in CTFs",
      "Some SQL injection payloads use reversed strings with REVERSE() function",
    ],
    relatedSlugs: ["rot13", "caesar", "base64"],
    notes: "Reversal is not encoding — it's a permutation. Combined encodings: first apply encoding, then reverse (or vice versa). Check for reversed Base64 strings ending with = before decoding.",
  },
  {
    slug: "lowercase",
    name: "Lowercase",
    description: "Convert all characters to lowercase",
    category: "Text",
    howItWorks: "All uppercase alphabetic characters are converted to their lowercase equivalents. Non-alphabetic characters and already-lowercase characters remain unchanged.",
    algorithm: "For each character, if it is an uppercase letter (A-Z), convert to its lowercase counterpart (a-z) by adding 32 to the ASCII value. Other characters are left as-is.",
    examples: [
      { input: "Hello World", output: "hello world" },
      { input: "XSS PAYLOAD", output: "xss payload" },
      { input: "Test123", output: "test123" },
    ],
    securityUseCases: [
      "Normalization — lowercase compares are standard in security testing",
      "Some case-sensitive WAF rules can be bypassed with mixed case",
      "SQL keywords are case-insensitive — lowercase queries still execute",
      "URL paths are case-sensitive on some servers (Linux) but not others (Windows)",
      "Normalizing to lowercase helps when comparing domain names and email addresses",
    ],
    relatedSlugs: ["uppercase", "reverse"],
    notes: "Most web operations are case-insensitive for HTML tags and SQL keywords. However, Base64 and hashes ARE case-sensitive. JavaScript is case-sensitive for variable names and function calls.",
  },
  {
    slug: "uppercase",
    name: "Uppercase",
    description: "Convert all characters to uppercase",
    category: "Text",
    howItWorks: "All lowercase alphabetic characters are converted to their uppercase equivalents. Non-alphabetic characters and already-uppercase characters remain unchanged.",
    algorithm: "For each character, if it is a lowercase letter (a-z), convert to its uppercase counterpart (A-Z) by subtracting 32 from the ASCII value. Other characters are left as-is.",
    examples: [
      { input: "Hello World", output: "HELLO WORLD" },
      { input: "xss payload", output: "XSS PAYLOAD" },
      { input: "Test123", output: "TEST123" },
    ],
    securityUseCases: [
      "SQL injection — some WAFs check for lowercase 'union select' but not 'UNION SELECT'",
      "XSS — <SCRIPT> executes same as <script> in most browsers",
      "Filter bypass — some input filters are case-sensitive",
      "HTTP header names are case-insensitive by RFC standard",
      "Normalization for comparison in security analysis workflows",
    ],
    relatedSlugs: ["lowercase", "reverse"],
    notes: "HTML tags and SQL keywords are case-insensitive. Base64 encoding produces different output for uppercase vs lowercase input. CJK characters and other scripts don't have case distinctions.",
  },
]

export const sidebarEncodingItems: { title: string; href: string }[] = [
  { title: "Base64", href: "/interactive/encoding-formats/base64" },
  { title: "Base64URL", href: "/interactive/encoding-formats/base64url" },
  { title: "Base32", href: "/interactive/encoding-formats/base32" },
  { title: "Base58", href: "/interactive/encoding-formats/base58" },
  { title: "Base85 / Ascii85", href: "/interactive/encoding-formats/base85" },
  { title: "URL", href: "/interactive/encoding-formats/url" },
  { title: "Double URL", href: "/interactive/encoding-formats/url-double" },
  { title: "HTML", href: "/interactive/encoding-formats/html" },
  { title: "HTML Hex", href: "/interactive/encoding-formats/html-hex" },
  { title: "HTML Decimal", href: "/interactive/encoding-formats/html-dec" },
  { title: "Hex", href: "/interactive/encoding-formats/hex" },
  { title: "Hex (spaces)", href: "/interactive/encoding-formats/hex-spaces" },
  { title: "Unicode \\u", href: "/interactive/encoding-formats/unicode-escape" },
  { title: "Unicode Code Point", href: "/interactive/encoding-formats/unicode-codepoint" },
  { title: "UTF-8 Bytes", href: "/interactive/encoding-formats/utf8-bytes" },
  { title: "JS \\x", href: "/interactive/encoding-formats/js-hex" },
  { title: "Morse Code", href: "/interactive/encoding-formats/morse" },
  { title: "Binary", href: "/interactive/encoding-formats/binary" },
  { title: "Octal", href: "/interactive/encoding-formats/octal" },
  { title: "ROT13", href: "/interactive/encoding-formats/rot13" },
  { title: "Caesar", href: "/interactive/encoding-formats/caesar" },
  { title: "Reverse", href: "/interactive/encoding-formats/reverse" },
  { title: "Lowercase", href: "/interactive/encoding-formats/lowercase" },
  { title: "Uppercase", href: "/interactive/encoding-formats/uppercase" },
]
