export interface GoogleDorkCategory {
  id: string
  title: string
  description: string
  dorks: { command: string; description: string }[]
}

export const lastUpdated = "2026-05-17"
export const pageDescription = "Deep Google Dorks — 247 dorks across 14 categories for advanced reconnaissance and vulnerability discovery."

export const googleDorksData: GoogleDorkCategory[] = [
  {
    id: "sensitive-files",
    title: "Sensitive Files & Data",
    description: "Leaked data, configs, and confidential documents — 30 dorks",
    dorks: [
      { command: 'site:example.com -www -shop -share -ir -mfa', description: "Broad domain search with negative filters" },
      { command: 'site:example.com ext:php inurl:?', description: "PHP files with parameters" },
      { command: 'site:"example.com" ext:log | ext:txt | ext:conf | ext:cnf | ext:ini | ext:env | ext:sh | ext:bak | ext:backup | ext:swp | ext:old | ext:~ | ext:git | ext:svn | ext:htpasswd | ext:htaccess | ext:json', description: "Configuration files and backups" },
      { command: 'site:example.com ext:txt | ext:pdf | ext:xml | ext:xls | ext:xlsx | ext:ppt | ext:pptx | ext:doc | ext:docx intext:"confidential" | intext:"Not for Public Release" | intext:"internal use only" | intext:"do not distribute"', description: "Confidential documents" },
      { command: 'inurl:email= | inurl:phone= | inurl:password= | inurl:secret= inurl:& site:example.com', description: "Sensitive parameters in URLs" },
      { command: 'site:example.com filetype:sql | filetype:db | filetype:dbf | filetype:mdb', description: "Database files" },
      { command: 'site:example.com inurl:"/wp-config.php" | inurl:"/.env" | inurl:"/config/"', description: "WordPress and application configuration files" },
      { command: 'site:example.com "index of" | "parent directory" | "directory listing"', description: "Directory listings" },
      { command: 'site:example.com filetype:key | filetype:pem | filetype:ppk | filetype:p12 | filetype:pfx | filetype:cer | filetype:crt', description: "Certificate and key files" },
      { command: 'site:example.com "BEGIN RSA PRIVATE KEY" | "BEGIN DSA PRIVATE KEY" | "BEGIN EC PRIVATE KEY" | "BEGIN OPENSSH PRIVATE KEY"', description: "Private keys in files" },
      { command: 'site:example.com filetype:properties intext:password | intext:username | intext:pass | intext:secret', description: "Properties files with credentials" },
      { command: 'site:example.com "robots.txt" | "sitemap.xml" | "crossdomain.xml" | "clientaccesspolicy.xml"', description: "Important configuration files" },
      { command: 'site:example.com filetype:yaml | filetype:yml intext:"database" | intext:"password" | intext:"secret" | intext:"key"', description: "YAML configuration files with sensitive data" },
      { command: 'site:example.com "access_token" | "refresh_token" | "client_secret" | "client_id" | "api_secret"', description: "OAuth and API credentials" },
      { command: 'site:example.com filetype:env | filetype:environment intext:"=" | intext:"password" | intext:"secret"', description: "Environment files with credentials" },
      { command: 'site:example.com "ftp://" | "sftp://" | "ssh://" | "telnet://" | "rdp://"', description: "Network protocol URLs" },
      { command: 'site:example.com "BEGIN CERTIFICATE" | "END CERTIFICATE" | "BEGIN PRIVATE KEY" | "END PRIVATE KEY"', description: "SSL certificates and private keys" },
      { command: 'site:example.com "password reset" | "forgot password" | "change password" | "reset link"', description: "Password reset functionality" },
      { command: 'site:example.com intext:"Internal Server Error" | intext:"500 Error" | intext:"403 Forbidden" | intext:"404 Not Found"', description: "HTTP error pages with information disclosure" },
      { command: 'site:example.com filetype:zip | filetype:rar | filetype:tar | filetype:gz | filetype:7z', description: "Archive files potentially containing source code" },
      { command: 'site:example.com "dump" | "backup" | "export" | "archive" | "snapshot"', description: "Database dumps and backup files" },
      { command: 'site:example.com "jenkins" | "gitlab" | "bamboo" | "teamcity" | "circleci"', description: "CI/CD platform references" },
      { command: 'site:example.com "elastic" | "logstash" | "kibana" | "elasticsearch" | "splunk"', description: "Log management and search platforms" },
      { command: 'site:example.com "docker-compose.yml" | "Dockerfile" | "kubernetes.yaml" | ".dockerignore"', description: "Container configuration files" },
      { command: 'site:example.com "ansible" | "puppet" | "chef" | "saltstack" | "terraform"', description: "Infrastructure automation tools" },
      { command: 'site:example.com ".git" | ".svn" | ".hg" | ".bzr" | "version control"', description: "Version control system files" },
      { command: 'site:example.com "node_modules" | "vendor" | "bower_components" | "packages"', description: "Package manager directories" },
      { command: 'site:example.com "localhost" | "127.0.0.1" | "0.0.0.0" | "internal network"', description: "Local and internal network references" },
      { command: 'site:example.com "staging" | "testing" | "development" | "sandbox" | "preprod"', description: "Non-production environment indicators" },
      { command: 'site:example.com "TODO" | "FIXME" | "BUG" | "HACK" | "NOTE"', description: "Developer comments and notes" },
    ],
  },
  {
    id: "vuln-params",
    title: "Vulnerability Parameters",
    description: "Injection points and parameter discovery — 30 dorks",
    dorks: [
      { command: 'inurl:q= | inurl:s= | inurl:search= | inurl:query= | inurl:keyword= | inurl:lang= inurl:& site:example.com', description: "XSS prone parameters" },
      { command: 'inurl:url= | inurl:return= | inurl:next= | inurl:redirect= | inurl:redir= | inurl:ret= | inurl:r2= | inurl:page= inurl:& inurl:http site:example.com', description: "Open Redirect prone parameters" },
      { command: 'inurl:id= | inurl:pid= | inurl:category= | inurl:cat= | inurl:action= | inurl:sid= | inurl:dir= inurl:& site:example.com', description: "SQL Injection prone parameters" },
      { command: 'inurl:http | inurl:url= | inurl:path= | inurl:dest= | inurl:html= | inurl:data= | inurl:domain= | inurl:page= inurl:& site:example.com', description: "SSRF prone parameters" },
      { command: 'inurl:include | inurl:dir | inurl:detail= | inurl:file= | inurl:folder= | inurl:inc= | inurl:locate= | inurl:doc= | inurl:conf= inurl:& site:example.com', description: "LFI prone parameters" },
      { command: 'inurl:cmd | inurl:exec= | inurl:query= | inurl:code= | inurl:do= | inurl:run= | inurl:read= | inurl:ping= inurl:& site:example.com', description: "RCE prone parameters" },
      { command: 'site:example.com intext:"sql syntax near" | intext:"syntax error has occurred" | intext:"incorrect syntax near" | intext:"unexpected end of SQL command" | intext:"Warning: mysql_connect()" | intext:"Warning: mysql_query()" | intext:"Warning: pg_connect()"', description: "SQL error messages" },
      { command: 'site:example.com intext:"Warning: include(" | intext:"Warning: require_once(" | intext:"Warning: require(" | intext:"Warning: include_once(" | intext:"failed to open stream"', description: "PHP inclusion errors" },
      { command: 'inurl:eval= | inurl:exec= | inurl:shell= | inurl:system= | inurl:passthru= | inurl:proc_open= site:example.com', description: "Code execution parameters" },
      { command: 'inurl:userid= | inurl:user_id= | inurl:customer_id= | inurl:member_id= | inurl:account_id= site:example.com', description: "User ID enumeration parameters" },
      { command: 'site:example.com inurl:"?id=" | inurl:"?user=" | inurl:"?category=" | inurl:"?product=" | inurl:"?page=" | inurl:"?item="', description: "Common vulnerable parameters" },
      { command: 'site:example.com intext:"blind sqli" | intext:"sql injection" | intext:"union select" | intext:"1=1" | intext:"or 1=1"', description: "SQL injection indicators" },
      { command: 'inurl:callback= | inurl:jsonp= | inurl:api_key= | inurl:access_token= | inurl:auth= site:example.com', description: "JSONP and API authentication parameters" },
      { command: 'inurl:template= | inurl:theme= | inurl:skin= | inurl:style= | inurl:layout= site:example.com', description: "Template and theme injection parameters" },
      { command: 'site:example.com inurl:"?" intext:"reflection" | intext:"mirror" | intext:"echo" | intext:"print"', description: "Parameter reflection and XSS testing" },
      { command: 'inurl:debug= | inurl:test= | inurl:demo= | inurl:dev= | inurl:stage= site:example.com', description: "Debug and development parameters" },
      { command: 'site:example.com inurl:"upload" inurl:"?" intext:"file" | intext:"image" | intext:"document"', description: "File upload vulnerability parameters" },
      { command: 'inurl:proxy= | inurl:gateway= | inurl:relay= | inurl:forward= | inurl:tunnel= site:example.com', description: "Proxy and tunneling parameters for SSRF" },
      { command: 'site:example.com "eval(" | "exec(" | "system(" | "shell_exec(" | "passthru(" | "popen("', description: "Dangerous PHP functions indicating RCE risks" },
      { command: 'inurl:log= | inurl:logs= | inurl:logfile= | inurl:audit= | inurl:trace= site:example.com', description: "Log file access parameters" },
      { command: 'site:example.com "XMLHttpRequest" | "fetch(" | "axios" | "ajax" | "$.get" | "$.post"', description: "Client-side request patterns for DOM XSS" },
      { command: 'inurl:admin= | inurl:user= | inurl:username= | inurl:userid= | inurl:uid= site:example.com', description: "User identification parameters" },
      { command: 'inurl:search= | inurl:query= | inurl:q= | inurl:keyword= | inurl:term= site:example.com', description: "Search functionality parameters" },
      { command: 'inurl:sort= | inurl:order= | inurl:orderby= | inurl:filter= | inurl:limit= site:example.com', description: "Data manipulation parameters" },
      { command: 'site:example.com "SELECT * FROM" | "INSERT INTO" | "UPDATE" | "DELETE FROM" | "DROP TABLE"', description: "SQL query fragments in responses" },
      { command: 'site:example.com "mysql_" | "mysqli_" | "pg_" | "oci_" | "sqlite_" | "mssql_"', description: "Database function calls" },
      { command: 'site:example.com "Warning:" | "Notice:" | "Error:" | "Fatal error:" | "Parse error:"', description: "PHP error messages" },
      { command: 'site:example.com "Traceback" | "Exception:" | "Error:" | "AttributeError:" | "ValueError:"', description: "Python error messages" },
      { command: 'site:example.com "java.lang" | "NullPointerException" | "ClassNotFoundException" | "SQLException"', description: "Java error messages" },
      { command: 'site:example.com "undefined method" | "undefined variable" | "undefined index" | "undefined offset"', description: "Undefined errors indicating code issues" },
    ],
  },
  {
    id: "api-endpoints",
    title: "API Endpoints & Services",
    description: "REST, GraphQL, and backend service discovery — 30 dorks",
    dorks: [
      { command: 'site:example.com inurl:api | site:*/rest | site:*/v1 | site:*/v2 | site:*/v3', description: "API endpoints" },
      { command: 'inurl:apidocs | inurl:api-docs | inurl:swagger | inurl:api-explorer site:"example.com"', description: "API documentation" },
      { command: 'site:example.com inurl:"/graphql" | inurl:"/graphiql"', description: "GraphQL endpoints" },
      { command: 'site:example.com filetype:wsdl | inurl:wsdl', description: "SOAP services" },
      { command: 'site:example.com inurl:"/api/v" | inurl:"/rest/v" | inurl:"/service/v"', description: "Versioned APIs" },
      { command: 'site:example.com intext:"api key" | intext:"api_key" | intext:"apikey"', description: "API key references" },
      { command: 'site:example.com inurl:"/oauth" | inurl:"/auth" | inurl:"/token"', description: "Authentication endpoints" },
      { command: 'site:example.com inurl:"/webhook" | inurl:"/callback"', description: "Webhook endpoints" },
      { command: 'site:example.com inurl:"/api/users" | inurl:"/api/admin" | inurl:"/api/login" | inurl:"/api/auth"', description: "Authentication API endpoints" },
      { command: 'site:example.com inurl:"/api/upload" | inurl:"/api/file" | inurl:"/api/download"', description: "File handling API endpoints" },
      { command: 'site:example.com "X-API-Key" | "Authorization: Bearer" | "API-Token" | "Access-Token"', description: "API authentication headers" },
      { command: 'site:example.com inurl:"/health" | inurl:"/status" | inurl:"/ping" | inurl:"/version"', description: "Service health endpoints" },
      { command: 'site:example.com inurl:"/api/test" | inurl:"/api/debug" | inurl:"/api/dev" | inurl:"/api/staging"', description: "Development and testing API endpoints" },
      { command: 'site:example.com "Content-Type: application/json" | "Accept: application/json" | "application/json"', description: "JSON API responses" },
      { command: 'site:example.com inurl:"/api/admin" | inurl:"/api/internal" | inurl:"/api/private" | inurl:"/api/management"', description: "Administrative API endpoints" },
      { command: 'site:example.com "cors" | "Access-Control-Allow-Origin" | "crossorigin" | "withCredentials"', description: "CORS configuration and headers" },
      { command: 'site:example.com inurl:"/websocket" | inurl:"/ws" | inurl:"/socket.io" | "WebSocket"', description: "WebSocket endpoints" },
      { command: 'site:example.com inurl:"/metrics" | inurl:"/prometheus" | inurl:"/monitoring" | inurl:"/telemetry"', description: "Monitoring and metrics endpoints" },
      { command: 'site:example.com "rate limit" | "quota exceeded" | "429" | "too many requests"', description: "Rate limiting information" },
      { command: 'site:example.com inurl:"/backup" | inurl:"/export" | inurl:"/download" | inurl:"/dump"', description: "Data export and backup endpoints" },
      { command: 'site:example.com "postman" | "insomnia" | "swagger.json" | "openapi.json" | "api-docs.json"', description: "API documentation and collection files" },
      { command: 'site:example.com inurl:"/graphql" | "query" | "mutation" | "subscription" | "GraphQL"', description: "GraphQL API endpoints and queries" },
      { command: 'site:example.com "REST" | "RESTful" | "endpoint" | "resource" | "HTTP methods"', description: "REST API documentation" },
      { command: 'site:example.com "authentication" | "authorization" | "oauth" | "jwt" | "bearer token"', description: "API authentication methods" },
      { command: 'site:example.com "rate limiting" | "throttling" | "quota" | "429 error" | "too many requests"', description: "API rate limiting information" },
      { command: 'site:example.com "webhook" | "callback" | "notification" | "event" | "trigger"', description: "Webhook and event-driven API features" },
      { command: 'site:example.com "API key" | "client secret" | "access token" | "refresh token"', description: "API credential references" },
      { command: 'site:example.com "curl" | "HTTP request" | "request example" | "code sample"', description: "API usage examples and code samples" },
      { command: 'site:example.com "beta" | "alpha" | "experimental" | "preview" | "unstable"', description: "Beta and experimental API features" },
      { command: 'site:example.com "deprecated" | "legacy" | "obsolete" | "discontinued" | "end of life"', description: "Deprecated API endpoints" },
    ],
  },
  {
    id: "server-errors",
    title: "Server Errors & Exceptions",
    description: "Error pages, stack traces, and debug info leaks — 17 dorks",
    dorks: [
      { command: 'inurl:"error" | intitle:"exception" | intitle:"failure" | intitle:"server at" | inurl:exception | "database error" | "SQL syntax" | "undefined index" | "unhandled exception" | "stack trace" site:example.com', description: "General server errors" },
      { command: 'site:example.com "Fatal error:" | "Parse error:" | "Warning:" | "Notice:"', description: "PHP errors" },
      { command: 'site:example.com "Server Error" | "Runtime Error" | "Microsoft OLE DB Provider" | "ASP.NET" | "Active Server Pages"', description: "ASP.NET errors" },
      { command: 'site:example.com "java.lang." | "java.util." | "java.io." | "Exception in thread"', description: "Java exceptions" },
      { command: 'site:example.com "Traceback" | "NameError" | "TypeError" | "ValueError" | "AttributeError"', description: "Python errors" },
      { command: 'site:example.com "ORA-" | "PLS-" | "TNS-" | "SP2-"', description: "Oracle database errors" },
      { command: 'site:example.com intitle:"500 Internal Server Error" | intitle:"404 Not Found" | intitle:"403 Forbidden"', description: "HTTP error pages" },
      { command: 'site:example.com "DEBUG" | "TRACE" | "ERROR" | "WARN" | "INFO" filetype:log', description: "Log files" },
      { command: 'site:example.com "Node.js" | "Express" | "Mongoose" | "MongoDB" | "Redis" intext:"error"', description: "Node.js and database errors" },
      { command: 'site:example.com "Laravel" | "Symfony" | "CodeIgniter" | "CakePHP" intext:"error" | intext:"exception"', description: "PHP framework errors" },
      { command: 'site:example.com "Django" | "Flask" | "FastAPI" | "Tornado" intext:"traceback" | intext:"error"', description: "Python framework errors" },
      { command: 'site:example.com "Spring" | "Hibernate" | "Struts" | "JSF" intext:"exception" | intext:"error"', description: "Java framework errors" },
      { command: 'site:example.com "nginx" | "apache" | "IIS" | "lighttpd" intext:"error" | intext:"403" | intext:"500"', description: "Web server error messages" },
      { command: 'site:example.com "memory leak" | "buffer overflow" | "segmentation fault" | "core dump"', description: "Memory and system errors" },
      { command: 'site:example.com "timeout" | "connection refused" | "network error" | "socket error"', description: "Network and connection errors" },
      { command: 'site:example.com "permission denied" | "access denied" | "unauthorized" | "forbidden"', description: "Access control errors" },
      { command: 'site:example.com "CSRF" | "cross-site" | "XSS" | "injection" | "vulnerable" intext:"error"', description: "Security-related error messages" },
    ],
  },
  {
    id: "admin-panels",
    title: "Admin Panels & Login Pages",
    description: "Admin interfaces, login portals, and CMS access — 19 dorks",
    dorks: [
      { command: 'inurl:login | inurl:signin | intitle:login | intitle:signin | inurl:secure site:example.com', description: "Login pages" },
      { command: 'site:example.com inurl:admin | inurl:administrator | inurl:wp-admin | inurl:phpmyadmin', description: "Admin panels" },
      { command: 'site:example.com inurl:"/control" | inurl:"/panel" | inurl:"/dashboard" | inurl:"/manage"', description: "Control panels" },
      { command: 'site:example.com "Select File" | "Browse" | "Drag and drop your file" | "Attach File" | "Select files" | "File upload" | "Upload your file" | "Submit File" | "Upload Documents" | "Upload Image"', description: "File upload forms and endpoints — Part 1" },
      { command: 'site:example.com "Drop files here to upload" | "Choose files to upload" | "Add File" | "Upload PDF" | "Upload Video" | "Upload Photo" | "Import File" | "Upload Resume"', description: "File upload forms and endpoints — Part 2" },
      { command: 'site:example.com "Upload files" | "Upload and Submit" | "Choose a file" | "Click to upload" | "Choose an image to upload"', description: "File upload forms and endpoints — Part 3" },
      { command: 'site:example.com intitle:"Admin" | intitle:"Administrator" | intitle:"Control Panel"', description: "Admin page titles" },
      { command: 'site:example.com inurl:"/wp-login.php" | inurl:"/wp-admin/" | inurl:"/administrator/"', description: "CMS admin areas" },
      { command: 'site:example.com intext:"forgot password" | intext:"reset password" | intext:"change password"', description: "Password reset pages" },
      { command: 'site:example.com inurl:"/cgi-bin/" | inurl:"/scripts/" | inurl:"/bin/"', description: "CGI and script directories" },
      { command: 'site:example.com "2FA" | "two factor" | "multi-factor" | "MFA" | "authenticator"', description: "Multi-factor authentication references" },
      { command: 'site:example.com inurl:"/backup" | inurl:"/restore" | inurl:"/recovery" | inurl:"/snapshot"', description: "Backup and recovery systems" },
      { command: 'site:example.com "maintenance mode" | "under construction" | "coming soon" | "temporarily unavailable"', description: "Maintenance and development pages" },
      { command: 'site:example.com inurl:"/test" | inurl:"/demo" | inurl:"/sample" | inurl:"/example"', description: "Test and demonstration pages" },
      { command: 'site:example.com "default password" | "admin:admin" | "root:root" | "password:password"', description: "Default credential references" },
      { command: 'site:example.com "session" | "cookie" | "token" | "csrf" | "xsrf"', description: "Session and token management" },
      { command: 'site:example.com inurl:"/setup" | inurl:"/install" | inurl:"/configure" | inurl:"/wizard"', description: "Installation and setup pages" },
      { command: 'site:example.com "sudo" | "root" | "administrator" | "superuser" | "privilege"', description: "Privileged access references" },
      { command: 'site:example.com inurl:"/reports" | inurl:"/analytics" | inurl:"/statistics" | inurl:"/dashboard"', description: "Reporting and analytics interfaces" },
    ],
  },
  {
    id: "cloud-storage",
    title: "Cloud Storage & Services",
    description: "AWS, Azure, GCP, and cloud-hosted assets — 21 dorks",
    dorks: [
      { command: 'site:s3.amazonaws.com "example.com"', description: "AWS S3 buckets" },
      { command: 'site:blob.core.windows.net "example.com"', description: "Azure Blob storage" },
      { command: 'site:googleapis.com "example.com"', description: "Google Cloud storage" },
      { command: 'site:drive.google.com "example.com"', description: "Google Drive files" },
      { command: 'site:dropbox.com/s "example.com"', description: "Dropbox shared files" },
      { command: 'site:box.com/s "example.com"', description: "Box.com shared files" },
      { command: 'site:docs.google.com inurl:"/d/" "example.com"', description: "Google Docs" },
      { command: 'site:firebaseio.com "example.com"', description: "Firebase databases" },
      { command: 'site:digitaloceanspaces.com "example.com"', description: "DigitalOcean Spaces" },
      { command: 'site:sharepoint.com "example.com"', description: "SharePoint sites" },
      { command: 'site:onedrive.live.com "example.com"', description: "OneDrive files" },
      { command: 'site:dev.azure.com "example.com"', description: "Azure DevOps" },
      { command: 'site:*.s3.amazonaws.com "example.com" | site:*.s3-us-west-2.amazonaws.com "example.com"', description: "Regional AWS S3 buckets" },
      { command: 'site:storage.googleapis.com "example.com" | site:*.storage.googleapis.com "example.com"', description: "Google Cloud Storage buckets" },
      { command: 'site:*.blob.core.windows.net "example.com" | site:*.file.core.windows.net "example.com"', description: "Azure Storage accounts" },
      { command: 'site:*.amazonaws.com "example.com" "bucket" | "key" | "secret"', description: "AWS services with credentials" },
      { command: 'site:heroku.com "example.com" | site:*.herokuapp.com "example.com"', description: "Heroku applications" },
      { command: 'site:*.netlify.app "example.com" | site:*.vercel.app "example.com"', description: "JAMstack hosting platforms" },
      { command: 'site:*.amazonaws.com "example.com" filetype:json | filetype:xml | filetype:txt', description: "AWS configuration files" },
      { command: 'site:cloudfront.net "example.com" | site:*.cloudfront.net "example.com"', description: "AWS CloudFront distributions" },
      { command: 'site:cdn.jsdelivr.net "example.com" | site:unpkg.com "example.com"', description: "CDN hosted files" },
    ],
  },
  {
    id: "code-leaks",
    title: "Code Leaks & Repositories",
    description: "Exposed source code, repos, and version control — 21 dorks",
    dorks: [
      { command: 'site:github.com "example.com" "password" | "secret" | "api_key"', description: "GitHub secrets referencing domain" },
      { command: 'site:github.com "example.com" "BEGIN RSA PRIVATE KEY"', description: "Private keys on GitHub" },
      { command: 'site:github.com "example.com" filename:.env', description: "Env files on GitHub" },
      { command: 'site:github.com "example.com" ".sql"', description: "SQL dumps on GitHub" },
      { command: 'site:gitlab.com "example.com" "password" | "secret"', description: "Secrets on GitLab" },
      { command: 'site:bitbucket.org "example.com" "password" | "secret"', description: "Secrets on Bitbucket" },
      { command: 'site:gist.github.com "example.com"', description: "GitHub Gists referencing domain" },
      { command: 'site:github.com "example.com" "bucket" "aws"', description: "AWS credentials on GitHub" },
      { command: 'site:github.com "example.com" "connectionString"', description: "Connection strings on GitHub" },
      { command: 'site:github.com "example.com" filename:.npmrc', description: "NPM config with tokens" },
      { command: 'site:github.com "example.com" "-----BEGIN CERTIFICATE-----"', description: "Certificates on GitHub" },
      { command: 'site:github.com "example.com" "slack_token" | "discord_webhook"', description: "Chat API tokens on GitHub" },
      { command: 'site:github.com "example.com" "password=" filetype:ini', description: "INI configs with passwords" },
      { command: 'site:github.com "example.com" "mongodb://" | "mongodb+srv://"', description: "MongoDB connection strings" },
      { command: 'site:gitlab.com "example.com" filename:.env', description: "Env files on GitLab" },
      { command: 'site:github.com "example.com" filename:credentials', description: "Credential files on GitHub" },
      { command: 'site:github.com "example.com" "jdbc:"', description: "JDBC connection strings" },
      { command: 'site:github.com "example.com" "redis://"', description: "Redis connection strings" },
      { command: 'site:github.com "example.com" "postgresql://"', description: "PostgreSQL connection strings" },
      { command: 'site:github.com "example.com" "S3_ACCESS_KEY" | "AWS_ACCESS_KEY"', description: "AWS key IDs on GitHub" },
      { command: 'site:gitlab.com "example.com" "-----BEGIN RSA PRIVATE KEY-----"', description: "Private keys on GitLab" },
    ],
  },
  {
    id: "infrastructure",
    title: "Infrastructure & Services",
    description: "Servers, monitoring, and network infrastructure — 17 dorks",
    dorks: [
      { command: 'site:example.com inurl:"/jenkins" | inurl:"/teamcity" | inurl:"/bamboo"', description: "CI/CD servers" },
      { command: 'site:example.com intitle:"Dashboard" inurl:"/grafana" | inurl:"/prometheus"', description: "Monitoring dashboards" },
      { command: 'site:example.com intitle:"kibana" | intitle:"elasticsearch"', description: "ELK stack interfaces" },
      { command: 'site:example.com inurl:"/phpmyadmin" | inurl:"/adminer" | inurl:"/pgadmin"', description: "Database management tools" },
      { command: 'site:example.com intitle:"phpinfo" | intitle:"phpinfo()"', description: "PHP info pages" },
      { command: 'site:example.com inurl:"/server-status" | inurl:"/server-info"', description: "Apache status pages" },
      { command: 'site:example.com intitle:"IIS" intitle:"Windows"', description: "IIS server pages" },
      { command: 'site:example.com "NGINX" | "nginx" intitle:"Welcome"', description: "Nginx welcome pages" },
      { command: 'site:example.com inurl:"/webmin" | inurl:"/cpanel" | inurl:"/plesk"', description: "Server management panels" },
      { command: 'site:example.com intitle:"Docker" inurl:"/containers"', description: "Docker management interfaces" },
      { command: 'site:example.com inurl:"/kibana" inurl:"/app/"', description: "Kibana dashboards" },
      { command: 'site:example.com inurl:"/zabbix" | inurl:"/nagios" | inurl:"/splunk"', description: "Monitoring platforms" },
      { command: 'site:example.com "UPnP" | "Cisco" | "router" intitle:"login"', description: "Network device interfaces" },
      { command: 'site:example.com inurl:"/console" | inurl:"/shell" | inurl:"/terminal"', description: "Console access pages" },
      { command: 'site:example.com inurl:"/api/health" | inurl:"/healthcheck"', description: "Health check endpoints" },
      { command: 'site:example.com intitle:"Swagger" | intitle:"API Documentation"', description: "API documentation UIs" },
      { command: 'site:example.com inurl:"/actuator" | inurl:"/actuator/health"', description: "Spring Boot Actuator endpoints" },
    ],
  },
  {
    id: "social-media",
    title: "Social Media & Public Info",
    description: "Exposed social media links and employee data — 10 dorks",
    dorks: [
      { command: 'site:linkedin.com "example.com"', description: "Employee LinkedIn profiles" },
      { command: 'site:twitter.com "example.com"', description: "Company Twitter/X references" },
      { command: 'site:facebook.com "example.com"', description: "Company Facebook pages" },
      { command: 'site:reddit.com "example.com"', description: "Reddit mentions" },
      { command: 'site:medium.com "example.com"', description: "Medium articles referencing domain" },
      { command: 'site:pastebin.com "example.com"', description: "Pastebin leaks" },
      { command: 'site:trello.com "example.com"', description: "Trello board references" },
      { command: 'site:notion.site "example.com"', description: "Notion pages with domain info" },
      { command: 'site:docs.google.com "example.com" "internal"', description: "Internal Google Docs" },
      { command: 'site:slack.com "example.com"', description: "Slack workspace references" },
    ],
  },
  {
    id: "security-research",
    title: "Security Research",
    description: "CTFs, bug bounty reports, and security advisories — 8 dorks",
    dorks: [
      { command: 'site:hackerone.com "example.com"', description: "HackerOne reports referencing domain" },
      { command: 'site:bugcrowd.com "example.com"', description: "Bugcrowd program references" },
      { command: 'site:intigriti.com "example.com"', description: "Intigriti program references" },
      { command: 'site:security.stackexchange.com "example.com"', description: "Security StackExchange mentions" },
      { command: 'site:exploit-db.com "example.com"', description: "Exploit-DB references" },
      { command: 'site:cve.mitre.org "example.com"', description: "CVE references" },
      { command: 'site:owasp.org "example.com"', description: "OWASP project mentions" },
      { command: 'site:github.com "example.com" "security.txt"', description: "Security.txt disclosure files" },
    ],
  },
  {
    id: "advanced-search",
    title: "Advanced Search Techniques",
    description: "Power search operators and filter combinations — 6 dorks",
    dorks: [
      { command: 'site:example.com -www -shop -share -ir -mfa -cdn -assets -static -img -css -js', description: "Broad exclusion filter" },
      { command: 'site:example.com intitle:"index of" "parent directory" -sample -test -demo', description: "Directory listing with exclusion" },
      { command: 'site:example.com ext:php | ext:asp | ext:aspx | ext:jsp | ext:cfm inurl:? intitle:"error" | intitle:"warning" | intext:"syntax"', description: "Dynamic pages with script errors" },
      { command: 'site:example.com filetype:json "webhook" | "callback" | "endpoint"', description: "JSON files with webhook configs" },
      { command: 'site:example.com inurl:"?" intitle:"test" | intitle:"debug" | intitle:"dev"', description: "Test and debug pages with params" },
      { command: 'site:example.com intext:"api_key" | intext:"apikey" | intext:"api-key" -github -gitlab -bitbucket', description: "API keys excluding code repos" },
    ],
  },
  {
    id: "mobile-iot",
    title: "Mobile & IoT Security",
    description: "Mobile app configs and Internet-connected devices — 24 dorks",
    dorks: [
      { command: 'site:example.com ext:apk | ext:aab', description: "Android APK/AAB files" },
      { command: 'site:example.com ext:ipa', description: "iOS IPA files" },
      { command: 'site:example.com filetype:plist', description: "iOS property list files" },
      { command: 'site:example.com "AndroidManifest.xml"', description: "Android manifest references" },
      { command: 'site:example.com "google-services.json"', description: "Firebase config files" },
      { command: 'site:example.com "GoogleService-Info.plist"', description: "iOS Firebase config files" },
      { command: 'site:example.com "app_name" "version" ext:json', description: "Mobile app config JSON" },
      { command: 'site:example.com "firebase" "database" ext:json', description: "Firebase database URLs" },
      { command: 'site:example.com "onesignal" "app_id"', description: "OneSignal push notification IDs" },
      { command: 'site:example.com "branch.io" | "adjust.com"', description: "Mobile attribution services" },
      { command: 'intitle:"webcam" "live" site:example.com', description: "Live webcams" },
      { command: 'intitle:"DVR" "login" site:example.com', description: "DVR login pages" },
      { command: 'inurl:"8080" intitle:"camera" site:example.com', description: "Camera interfaces on port 8080" },
      { command: 'site:example.com intitle:"Network Camera" | intitle:"IP Camera"', description: "IP camera interfaces" },
      { command: 'site:example.com intitle:"Wireless" "access point"', description: "Wireless access points" },
      { command: 'site:example.com "smart TV" | "smart device" | "IoT"', description: "IoT device references" },
      { command: 'site:example.com "MQTT" | "coap://" | "dns-sd"', description: "IoT protocol references" },
      { command: 'site:example.com "android" "debug" "keystore"', description: "Android debug keystores" },
      { command: 'site:example.com "ProGuard" "mapping.txt"', description: "ProGuard mapping files" },
      { command: 'site:example.com inurl:"/.well-known/assetlinks.json"', description: "Android app link verification" },
      { command: 'site:example.com inurl:"/.well-known/apple-app-site-association"', description: "iOS universal links config" },
      { command: 'site:example.com "com.apple" "aps-environment" ext:plist', description: "iOS push notification configs" },
      { command: 'site:example.com "REST_API" ext:json "android"', description: "Mobile API endpoints" },
      { command: 'site:example.com "api/v2" "android" | "ios"', description: "Mobile-specific API versions" },
    ],
  },
  {
    id: "crypto-blockchain",
    title: "Cryptocurrency & Blockchain",
    description: "Crypto wallets, smart contracts, and blockchain references — 14 dorks",
    dorks: [
      { command: 'site:example.com "bitcoin" | "ethereum" | "crypto" intext:"wallet"', description: "Crypto wallet references" },
      { command: 'site:example.com "0x" "wallet" erc-20 | erc-721', description: "Ethereum wallet addresses" },
      { command: 'site:example.com "mnemonic" | "seed phrase" | "private key" crypto', description: "Crypto seed phrases and private keys" },
      { command: 'site:example.com "metamask" | "trust wallet" | "ledger"', description: "Crypto wallet app configs" },
      { command: 'site:example.com "blockchain" "api key" | "api_key"', description: "Blockchain API keys" },
      { command: 'site:example.com "INFURA" | "alchemy" "api"', description: "Blockchain infrastructure API keys" },
      { command: 'site:example.com "coinbase" | "binance" "api"', description: "Exchange API references" },
      { command: 'site:example.com "smart contract" "address"', description: "Smart contract addresses" },
      { command: 'site:example.com "solidity" "contract" filetype:sol', description: "Solidity source files" },
      { command: 'site:example.com "ICO" "token" "sale"', description: "ICO and token sale references" },
      { command: 'site:example.com "NFT" "collection" "contract"', description: "NFT contract addresses" },
      { command: 'site:example.com "cold wallet" | "hot wallet" | "hardware wallet"', description: "Wallet type references" },
      { command: 'site:example.com "crypto" "exchange" "api"', description: "Crypto exchange API docs" },
      { command: 'site:example.com "decentralized" "app" "dapp"', description: "DApp references" },
    ],
  },
]
