import {
  Search,
  Bug,
  Server,
  Cloud,
  Wrench,
  Brain,
  Shield,
  Puzzle,
  Terminal,
  Siren,
  Target,
  Zap,
  Globe,
  Lock,
  Database,
  Code,
  FolderSearch,
  Network,
  Key,
} from "lucide-react"

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  search: Search,
  bug: Bug,
  server: Server,
  cloud: Cloud,
  wrench: Wrench,
  brain: Brain,
  shield: Shield,
  puzzle: Puzzle,
  terminal: Terminal,
  siren: Siren,
  target: Target,
  zap: Zap,
  globe: Globe,
  lock: Lock,
  database: Database,
  code: Code,
  "folder-search": FolderSearch,
  network: Network,
  key: Key,
}
